<?php use Chiara\Core\ViewModel;?>



	<div class="box pad">
		<h2 class="title">Chiara Server Framework</h2>
			<div class="pad">
				Server side has everything you need to make any kind of web service.<br />
				Request Routing, Caching, DB Conncetion, Translation e more.<br />
				Chiara Server side inspired by the most famous Zend Framework maintaining the basic operation, but much lighter. 
			</div>
	</div>
