<?php use Chiara\Core\ViewModel;?>



	<div class="box pad">
		<h2 class="title">AJAX Request</h2>
			<div class="pad">
				For AJAX request you can use <strong>Chiara.req</strong> object.<br />
				
				<h4>AJAX POST</h4>
				<pre>
					<code class="javascript">
// Chiara.req.post(url, data, callback, timeout);
Chiara.req.post('/context/path/address', {param1:value1, param2:value2}, function(d){
	// d is the returned JSON data
	// ...
});
					</code>
				</pre>
				You can set a context root valid for all request:
				
				<pre>
					<code class="javascript">
Chiara.req.opt.baseUrl = '/context';
Chiara.req.post('/path/address');
					</code>
				</pre>
				
				<h4>Link POST</h4>
				<pre>
					<code class="javascript">
// Chiara.req.linkPost(url, data, target);
Chiara.req.linkPost('/path/address', [{name:'param1', value:'value1'}, {name:'param2', value:'value2'}], '_blank');
					</code>
				</pre>
			</div>
	</div>
			
