<?php 
use Chiara\Core\ViewModel;
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Chiara</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
	<link href="<?php echo ViewModel::getOption('urlbase') ?>/css/interface.css" media="screen" rel="stylesheet" type="text/css"/>
	<link href="<?php echo ViewModel::getOption('urlbase') ?>/css/qtip.min.css" media="screen" rel="stylesheet" type="text/css"/>
	<link href="<?php echo ViewModel::getOption('urlbase') ?>/css/xcode.css" media="screen" rel="stylesheet" type="text/css"/>
    <link href="<?php echo ViewModel::getOption('urlbase') ?>/css/style.css" media="screen" rel="stylesheet" type="text/css"/>
	
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/jquery-2.1.3.min.js" type="text/javascript"></script>
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/jquery.qtip.min.js" type="text/javascript"></script>
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/highlight.pack.js" type="text/javascript"></script>
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/interface.js" type="text/javascript"></script>
</head>
<body>
	<?php ViewModel::getContents(); ?>
</body>
</html>