<?php 
use Chiara\Core\ViewModel;
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Chiara demo/documentation <?php echo ViewModel::getOption('pageTitle') ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
	<link href="<?php echo ViewModel::getOption('urlbase') ?>/css/chiara.css" media="screen" rel="stylesheet" type="text/css"/>
	<link href="<?php echo ViewModel::getOption('urlbase') ?>/css/qtip.min.css" media="screen" rel="stylesheet" type="text/css"/>
	<link href="<?php echo ViewModel::getOption('urlbase') ?>/css/xcode.css" media="screen" rel="stylesheet" type="text/css"/>
    <link href="<?php echo ViewModel::getOption('urlbase') ?>/css/style.css" media="screen" rel="stylesheet" type="text/css"/>
	
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/jquery-2.1.3.min.js" type="text/javascript"></script>
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/jquery.qtip.min.js" type="text/javascript"></script>
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/highlight.pack.js" type="text/javascript"></script>
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/chiara.js" type="text/javascript"></script>
</head>
<body>

	<div id="UserMessageBox"></div>

	<div class="section group wrapper">
		<div class="col span_1_of_4">
			<?php ViewModel::getContents('site/menu'); ?>
		</div>
		
		<div class="col span_3_of_4">
		
			<?php ViewModel::getContents('site/header'); ?>
		
			<div class="content">
			<?php ViewModel::getContents(); ?>
			</div>

			<?php ViewModel::getContents('site/footer'); ?>
		</div>
	</div>


	
</body>
</html>