<?php 
use Chiara\Core\ViewModel;
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Chiara Docs <?php echo ViewModel::getOption('pageTitle') ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
	<link href="<?php echo ViewModel::getOption('urlbase') ?>/css/chiara.css" media="screen" rel="stylesheet" type="text/css"/>
	<link href="<?php echo ViewModel::getOption('urlbase') ?>/css/qtip.min.css" media="screen" rel="stylesheet" type="text/css"/>
	<link href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/xcode.min.css" rel="stylesheet" >
    <link href="<?php echo ViewModel::getOption('urlbase') ?>/css/style.css" media="screen" rel="stylesheet" type="text/css"/>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/jquery.qtip.min.js" type="text/javascript"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/chiara.js" type="text/javascript"></script>
	<script src="<?php echo ViewModel::getOption('urlbase') ?>/js/app.js" type="text/javascript"></script>
</head>
<body>

	<div id="UserMessageBox"></div>

	<div class="section group wrapper">
		<div class="col span_1_of_4">
			<?php ViewModel::getContents('site/menu'); ?>
		</div>
		
		<div class="col span_3_of_4">
		
			<?php ViewModel::getContents('site/header'); ?>
		
			<div class="content">
			<?php ViewModel::getContents(); ?>
			</div>

			<?php ViewModel::getContents('site/footer'); ?>
		</div>
	</div>

	<script type="text/javascript">$(document).ready(app.init);</script>
	
</body>
</html>