<?php 
use Chiara\Core\ViewModel;
ViewModel::getContents('site/header');
?>

<div class="section group" id="main">
	<div class="col span_1_of_5">
		<ul class="leftmenu">
			<li><a href="#SGri">AJAX request</a></li>
			<li><a href="#SGri">Link javascript</a></li>
			<li><a href="#SSec">Paginator</a></li>
			<li><a href="#SSec">Fast messages</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SWin')">Overlay message</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SWin')">Modal windows</a></li>
			<li><a href="#SSec">Scroll</a></li>
			<li><a href="#SSec">isOffScreen</a></li>
			<li><a href="#SSec">Checklist</a></li>
			<li><a href="#SSec">Seach on List</a></li>
			<li><a href="#SSec">Form utility</a></li>
		</ul>
	</div>
	<div class="col span_4_of_5">

			<h1>Client side documentation</h1>

			<h2>AJAX Request</h2>
			<div class="box padd" name="SGri">
				For AJAX request you can use <strong>Chiara.req</strong> object.<br />
				
				<h4>AJAX POST</h4>
				<pre>
					<code class="javascript">
// Chiara.req.post(url, data, callback, timeout);
Chiara.req.post('/context/path/address', {param1:value1, param2:value2}, function(d){
	// d is the returned data... JSON
	// ...
});
					</code>
				</pre>
				You can set a context root valid for all request:
				
				<pre>
					<code class="javascript">
Chiara.req.opt.baseUrl = '/context';
Chiara.req.post('/path/address');
					</code>
				</pre>
				
				<h4>Link POST</h4>
				<pre>
					<code class="javascript">
// Chiara.req.linkPost(url, data, target);
Chiara.req.linkPost('/path/address', [{name:'param1', value:'value1'}, {name:'param2', value:'value2'}], '_blank');
					</code>
				</pre>
				
			</div>
			
			
			<h2>Fast messages</h2>
			<div class="box padd" name="SSec">	
				Show fast message alert on the screen
				<pre>
					<code class="javascript">
Chiara.msg.showFast({
				text:'Test user fast message', 
				description:'This is an optional description', 
				buttons:[{
					value:'A Button', 
					action: 'alert(\'Hello!\')'
				},{
					value:'Green button', 
					type: 'green',
					action: 'alert(\'Hello Green!\')'
				},{
					value:'Red button', 
					type: 'red',
					action: 'alert(\'Hello Red!\')'
				}], 
				level:6});
					</code>
				</pre>
				<button class="btn" onclick="Chiara.msg.showFast({text:'Test user fast message', description:'This is an optional description',level:6, buttons:[{value:'A Button', action: 'alert(\'Hello!\')'},{value:'Green button', type: 'green',action: 'alert(\'Hello Green!\')'},{value:'Red button', type: 'red',action: 'alert(\'Hello Red!\')'}]})">Test</button>
			</div>
			
			<h2>Overlay messages</h2>
			<div class="box padd" name="SSec">	
				Show fast message alert on the screen
				<pre>
					<code class="javascript">
Chiara.msg.showOverlay({
				text:'Test user overlay message', 
				description:'This is an optional description', 
				buttons:[{
					value:'A Button', 
					action: 'alert(\'Hello!\')'
				},{
					value:'Green button', 
					type: 'green',
					action: 'alert(\'Hello Green!\')'
				},{
					value:'Red button', 
					type: 'red',
					action: 'alert(\'Hello Red!\')'
				}], 
				level:6});
					</code>
				</pre>
				<button class="btn" onclick="Chiara.msg.showOverlay({text:'Test user overlay message', description:'This is an optional description',level:6, buttons:[{value:'A Button', action: 'alert(\'Hello!\')'},{value:'Green button', type: 'green',action: 'alert(\'Hello Green!\')'},{value:'Red button', type: 'red',action: 'alert(\'Hello Red!\')'}]})">Test</button>
			</div>
			
			<h2>Modal windows</h2>
			<div class="box padd" id="SWin">
				Open modal window and overlay window
				<button class="btn" onclick="Chiara.modal.open('#WindowExample');">Open modal</button>
			</div>
			
			
			<h2>Paginator</h2>
			<div class="box padd" id="SPag">
				<pre>
					<code class="javascript">
Chiara.paginator('Paginator',{currentPage:1, pgTotalPage:10, pgTotalItem:5},'null');
					</code>
				</pre>
				<div id="Paginator"></div>
			</div>
			
			<h2>Scroll</h2>
			<div class="box padd" id="SPag">
				
			</div>
			
			<h2>isOffScreen</h2>
			<div class="box padd" id="SPag">
				
			</div>
			
			<h2>Checklist</h2>
			<div class="box padd" id="SPag">
				
			</div>
			
			<h2>Seach on List</h2>
			<div class="box padd" id="SPag">
				
			</div>
			
			<h2>Form utility</h2>
			<div class="box padd" id="SPag">
				
			</div>
			
	</div>
</div>



<div class="modal" id="WindowExample">
	<div class="modal-head">
		<button class="close" onclick="Chiara.modal.close();">x</button>
    	<h3>Modal window example</h3>
	</div>
	<div class="modal-body">
		Text and content
	</div>
	<div class="modal-foot">
		<div class="section group">
			<div class="col span_1_of_3 left">
				 <button class="btn btn-red" onclick=";">Left button</button>
			</div>
			<div class="col span_2_of_3">
				<button class="btn" onclick="Chiara.modal.close();">Done</button>
				<button class="btn btn-green" onclick="Chiara.modal.close();">Ok</button>
			</div>
		</div>
		
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	Chiara.paginator('Paginator',{currentPage:1, pgTotalPage:10, pgTotalItem:5},'null');
});
</script>

<?php ViewModel::getContents('site/footer');  ?>

