<?php 
use Chiara\Core\ViewModel;
ViewModel::getContents('site/header');
?>

<div class="section group" id="main">
	<div class="col span_1_of_5">
		<ul class="leftmenu">
			<li><a href="#SGri">AJAX request</a></li>
			<li><a href="#SSec">User messages</a></li>
			<li><a href="#SSec">File upload</a></li>
		</ul>
	</div>
	<div class="col span_4_of_5">

			<h1>Client side documentation</h1>

			<div class="box padd mrggh" name="SGri">
				<h2>AJAX Request</h2>
				
			</div>
			
			<div class="box padd mrggh" name="SSec">
				<h2>User messages</h2>
				
			</div>
			
			<div class="box padd mrggh" name="STyp">
				<h2>File upload</h2>
				
			</div>
			
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	
});
</script>

<?php ViewModel::getContents('site/footer');  ?>

