<?php 
use Chiara\Core\ViewModel;
ViewModel::getContents('site/header');
?>

<div class="section group" id="main">
	<div class="col span_1_of_5">
		<ul class="leftmenu">
			<li><a href="#S" onclick="Chiara.scrollTo('#SSce')">Scenario</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SFol')">Folders tree</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SCon')">Configuration</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SLoa')">Index.php / Loader</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SRou')">Routing</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SIni')">Init</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SCtr')">Controller</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SVie')">View</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SLay')">Layout</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SMod')">Model</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SSes')">Session</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SCac')">Cache</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SGlo')">Globals</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SHtt')">Http</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SFil')">File transfer</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SVal')">Validators</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SDat')">Date helper</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SDri')">Database driver</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SSys')">File system</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SLog')">Log</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#SMes')">Message</a></li>
			<li><a href="#S" onclick="Chiara.scrollTo('#STra')">Translator I18n</a></li>
			</ul>
	</div>
	<div class="col span_4_of_5">

			<h1>Server side documentation</h1>

			<h3>Scenario</h3>
			<div class="box padd" id="SSce">
				
				Chiara is a complete framework to develop any web service type.<br />
				It's a MVC framework.
				Every request is dispatched to a specific action controller by the router:<br /><br />
				
				<strong>http://www.example.com/&lt;controller&gt;/&lt;action&gt;</strong>
			</div>
			
			<h3>Folders tree</h3>
			<div class="box padd" id="SFol">
				
				Chiara is a library that can be used externally to your application. Here is exhibited a masting of example for writing applications.
				
				<strong>/application</strong>
				Really server side application<br /><br />
				<strong>/application/Config</strong>
				configuration files<br /><br />
				<strong>/application/Controller</strong>
				Controllers<br /><br />
				<strong>/application/Layout</strong>
				Layout tamplate page<br /><br />
				<strong>/application/Model</strong>
				Model classes<br /><br />
				<strong>/application/View</strong>
				Views<br /><br />
				<strong>/public</strong>
				Index.php, css, javascript and images
			</div>
			
			
			<h3>Configuration</h3>
			<div class="box padd" id="SCon">
				
				The only configuration you need is /application/configuration/configuration.php as a PHP Array
				
				<pre>
					<code class="php">
$config = array(
	'config' => array(
		"controllerAccess" 	=> "ctrl", # post controller param name
		"actionAccess" 	=> "act", # post action param name
		"controllers" 		=> array( # Exposed controller 
			array("classname" => "App\\Controllers\\SiteCtrl", "context" => "/"),
			array("classname" => "App\\Controllers\\SiteCtrl", "context" => "/site"),
			array("classname" => "App\\Controllers\\ErrorCtrl", "context" => "/error"),
			array("classname" => "App\\Controllers\\TestCtrl", "context" => "/test")
		),
		"params" 			=> array(
				"Param1" 	=> true,
				"Param2" 	=> 34,
				'ConfigFile' 	=> BASE_DIR . '/demo/application/config/demo.config.ini',
				'LogFile' 	=> BASE_DIR . '/demo/demo.log'
		)
	)
);
					</code>
				</pre>
				
			</div>
			
			<h3>Index.php / Loader</h3>
			<div class="box padd" id="SLoa">
				
				The start point of a PHP application is always the index.php file...<br />
				<pre>
					<code class="php">
define('BASE_DIR', realpath(dirname(__FILE__) . '/../..'));

// Loading Chiara and other external library
require_once( BASE_DIR . '/src/NLoader.php');
$nLoader = new Chiara\NLoader();
$nLoader->letsInclude( BASE_DIR . '/demo/application/config/defines.php');
$nLoader->addNamespace( 'App',  BASE_DIR . '/demo/application');
$nLoader->load();

// Set and run application
$app = new App\Init(__FILE__);
$app->setConfiguration(BASE_DIR . '/demo/application/Config/configuration.php', 'ARRAY');
$app->setViewsDir(BASE_DIR . '/demo/application/Views');
$app->setLayoutsDir(BASE_DIR . '/demo/application/Layouts');
$app->run();
					</code>
				</pre>
				
			</div>
			
			<h3>Routing</h3>
			<div class="box padd" id="SRou">
				
				
			</div>
			
			<h3>Init</h3>
			<div class="box padd" id="SIni">
				Init.php is the specific class /application/Init.php<br />
				It is executed every request on head of everything, after the run call, to initialize application.<br />
				In this class is executed by Chiara, every method that start with init...
				
				<pre>
					<code class="php">
class Init extends InitAbstract{
	
	public function initError() {
		// ...	    
	}
	
	// ...
}
					</code>
				</pre>
				
			</div>
			
			<h3>Controller</h3>
			<div class="box padd" id="SCtr">
				Controllers contain the action exposed by service.<br />
				Every public method that end with ...Action() is an action. Usually it end with an HTML page or a JSON to serve.<br />
				When a controller is dispatched the routing execute always the init method (if exist) and after the action required.
				
				<pre>
					<code class="php">
class TestCtrl extends ControllerAbstract{
	
	public function init(){
		// ...
	}
	
	public function indexAction(){
		// ...
	}
	
	public function clientAction(){
		// ...
	}
}
					</code>
				</pre>
				
				
			</div>
			
			<h3>View</h3>
			<div class="box padd" id="SRVie">
				ViewModel is the class that prepare the response and serve it to client.<br />
				It can processing PHTML template, JSON response or File to download.<br />
				
			</div>
			
			<h3>Layout</h3>
			<div class="box padd" id="SLay">
				Layout is the wrapper template.
				
			</div>
			
			<h3>Model</h3>
			<div class="box padd" id="SMod">
				Models ... from MVC ;)
				
			</div>
			
			<h3>Session</h3>
			<div class="box padd" id="SSes">
				Chiara has a session management
				
			</div>
			
			<h3>Cache</h3>
			<div class="box padd" id="SCac">
				
				
			</div>
			
			<div class="box padd" id="SGlo">
				<h2>Global</h2>
				
			</div>
			
			<div class="box padd" id="SHtt">
				<h2>Http helper</h2>
				
			</div>
			
			<div class="box padd" id="SFil">
				<h2>File transfer</h2>
				
			</div>
			
			<div class="box padd" id="SVal">
				<h2>Validators</h2>
				
			</div>
			
			<div class="box padd" id="SDat">
				<h2>Date helper</h2>
				
			</div>
			
			<div class="box padd" id="SDri">
				<h2>Database driver</h2>
				
			</div>
			
			<div class="box padd" id="SSys">
				<h2>File system</h2>
				
			</div>
			
			<div class="box padd" id="SLog">
				<h2>Log</h2>
				
			</div>
			
			<div class="box padd" id="SMes">
				<h2>Message</h2>
				
			</div>
			
			<div class="box padd" id="STra">
				<h2>Translator I18n</h2>
				
			</div>
			
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
	
});
</script>

<?php ViewModel::getContents('site/footer');  ?>

