<?php 
use Chiara\Core\ViewModel;
ViewModel::getContents('site/header');
?>

<div class="section group" id="main">
	<div class="col span_1_of_5">
		<ul class="leftmenu">
			<li><a href="#" onclick="Chiara.scrollTo('#SGri')">Grids</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SSec')">Sections</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#STyp')">Typography</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#STab')">Tables</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SFor')">Forms</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SBut')">Buttons</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SToo')">Tooltip</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SLab')">Label</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SWin')">Window</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SAle')">Alert</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SIco')">Icons</a></li>
			<li><a href="#" onclick="Chiara.scrollTo('#SPag')">Paginator</a></li>
		</ul>
	</div>
	<div class="col span_4_of_5">

			<h1>Demo Test Page</h1>

			<div class="box padd mrggh" id="SGri">
				<h2>Grids</h2>
				
				<div class="gridtest">

						<div class="section group">
							<h4>Two Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_2">1 of 2</div>
							<div class="col span_1_of_2">1 of 2</div>
						</div>

						<div class="section group">
							<h4>Three Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_3">1 of 3</div>
							<div class="col span_1_of_3">1 of 3</div>
							<div class="col span_1_of_3">1 of 3</div>
						</div>

						<div class="section group">
							<h4>Four Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_4">1 of 4</div>
							<div class="col span_1_of_4">1 of 4</div>
							<div class="col span_1_of_4">1 of 4</div>
							<div class="col span_1_of_4">1 of 4</div>
						</div>

						<div class="section group">
							<h4>Five Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_5">1 of 5</div>
							<div class="col span_1_of_5">1 of 5</div>
							<div class="col span_1_of_5">1 of 5</div>
							<div class="col span_1_of_5">1 of 5</div>
							<div class="col span_1_of_5">1 of 5</div>
						</div>

						<div class="section group">
							<h4>Six Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_6">1 of 6</div>
							<div class="col span_1_of_6">1 of 6</div>
							<div class="col span_1_of_6">1 of 6</div>
							<div class="col span_1_of_6">1 of 6</div>
							<div class="col span_1_of_6">1 of 6</div>
							<div class="col span_1_of_6">1 of 6</div>
						</div>

						<div class="section group">
							<h4>Seven Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_7">1 of 7</div>
							<div class="col span_1_of_7">1 of 7</div>
							<div class="col span_1_of_7">1 of 7</div>
							<div class="col span_1_of_7">1 of 7</div>
							<div class="col span_1_of_7">1 of 7</div>
							<div class="col span_1_of_7">1 of 7</div>
							<div class="col span_1_of_7">1 of 7</div>
						</div>

						<div class="section group">
							<h4>Eight Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_8">1 of 8</div>
							<div class="col span_1_of_8">1 of 8</div>
							<div class="col span_1_of_8">1 of 8</div>
							<div class="col span_1_of_8">1 of 8</div>
							<div class="col span_1_of_8">1 of 8</div>
							<div class="col span_1_of_8">1 of 8</div>
							<div class="col span_1_of_8">1 of 8</div>
							<div class="col span_1_of_8">1 of 8</div>
						</div>

						<div class="section group">
							<h4>Nine Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_9">1 of 9</div>
							<div class="col span_1_of_9">1 of 9</div>
							<div class="col span_1_of_9">1 of 9</div>
							<div class="col span_1_of_9">1 of 9</div>
							<div class="col span_1_of_9">1 of 9</div>
							<div class="col span_1_of_9">1 of 9</div>
							<div class="col span_1_of_9">1 of 9</div>
							<div class="col span_1_of_9">1 of 9</div>
							<div class="col span_1_of_9">1 of 9</div>
						</div>

						<div class="section group">
						<h4>Ten Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_10">1 of 10</div>
							<div class="col span_1_of_10">1 of 10</div>
							<div class="col span_1_of_10">1 of 10</div>
							<div class="col span_1_of_10">1 of 10</div>
							<div class="col span_1_of_10">1 of 10</div>
							<div class="col span_1_of_10">1 of 10</div>
							<div class="col span_1_of_10">1 of 10</div>
							<div class="col span_1_of_10">1 of 10</div>
							<div class="col span_1_of_10">1 of 10</div>
							<div class="col span_1_of_10">1 of 10</div>
						</div>

						<div class="section group">
						<h4>Eleven Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_11">1 of 11</div>
							<div class="col span_1_of_11">1 of 11</div>
							<div class="col span_1_of_11">1 of 11</div>
							<div class="col span_1_of_11">1 of 11</div>
							<div class="col span_1_of_11">1 of 11</div>
							<div class="col span_1_of_11">1 of 11</div>
							<div class="col span_1_of_11">1 of 11</div>
							<div class="col span_1_of_11">1 of 11</div>
							<div class="col span_1_of_11">1 of 11</div>
							<div class="col span_1_of_11">1 of 11</div>
							<div class="col span_1_of_11">1 of 11</div>
						</div>


						<div class="section group">
						<h4>Twelve Columns</h4>
						</div>

						<div class="section group">
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
							<div class="col span_1_of_12">1 of 12</div>
						</div>
					</div>

			</div>
			
			<div class="box padd mrggh" id="SSec">
				<h2>Sections</h2>
				
				<div class="box brd pad mrg">
					Borded and padded
				</div>
				
				<div class="box brd pad mrg">
					<div class="title">Titled</div>
					Borded, padded ...
				</div>
				
				<div class="box brd pad mrg rnd">
					<div class="title">Titled</div>
					and rounded
				</div>
			</div>
			
			<div class="box padd mrggh" id="STyp">
				<h2>Typography</h2>
				<div class="box pad mrg">
					<h1>Heading 1</h1>
					<h2>Heading 2</h2>
					<h3>Heading 3</h3>
					<h4>Heading 4</h4>
					<h5>Heading 5</h5>
					<h6>Heading 6</h6>
					<p>Normal text</p>
					<strong>Strong text</strong><br />
					<small>Small text</small><br />
					
				</div>
			</div>
			
			<div class="box padd mrggh" id="STab">
				<h2 class="">Tables</h2>
				
				<table class="line hover">
					<thead>
						<tr>
							<th>Col 1</th>
							<th>Col 2</th>
							<th>Col 3</th>
							<th>Col 4</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Cell</td>
							<td>Cell</td>
							<td>Cell</td>
							<td>Cell</td>
						</tr>
						<tr>
							<td>Cell</td>
							<td>Cell</td>
							<td>Cell</td>
							<td>Cell</td>
						</tr>
					</tbody>
				</table>
			
			</div>
			
			<div class="box padd mrggh" id="SFor">
				<h2>Forms</h2>
				<div class="section group">
					<div class="col span_1_of_3">
						Text field
					</div>
					<div class="col span_2_of_3">
						<input type="text" />
					</div>
				</div>
				
				<div class="section group">
					<div class="col span_1_of_3">
						 a checkbox
					</div>
					<div class="col span_2_of_3">
						<input type="checkbox" />
					</div>
				</div>
				
				<div class="section group">
					<div class="col span_1_of_3">
						 a select
					</div>
					<div class="col span_2_of_3">
						<select>
							<option>one</option>
							<option>two</option>
							<option>tree</option>
							<option>four</option>
						</select>
					</div>
				</div>
				
			</div>
			
			<div class="box padd mrggh" id="SBut">
				<h2>Buttons</h2>
				<button class="btn btn-mini">Ok mini button</button> 
				<button class="btn btn-small">Ok small button</button> 
				<button class="btn">Ok button</button> 
				<button class="btn btn-large">Ok large button</button>
				
				<br />
				
				<button class="btn btn-green">Green button</button>
				<button class="btn btn-red">Red button</button>
				<button class="btn btn-blue">Blue button</button>
				<button class="btn btn-orange">Orange button</button>
				<button class="btn btn-celeste">Celeste button</button>
				<button class="btn btn-black">Black button</button>
				
			</div>
			
			<div class="box padd mrggh" id="SToo">
				<h2>Tooltips</h2>
				For tooltip Chiara inglobe <a href="http://qtip2.com/" target="_blank">qTip2</a>
			</div>
			
			<div class="box padd mrggh" id="SWin">
				<h2>Windows</h2>
				Open modal window and overlay messages
				<button class="btn" onclick="Chiara.modal.open('#WindowExample');">Open modal</button>
			</div>
			
			<div class="box padd mrggh" id="SLab">
				<h2>Fast messages</h2>
				
				<div class="alert">This is a message</div>
				<div class="alert alert-green">This is an other message</div>
				<div class="alert alert-celeste">This is an other message</div>
				<div class="alert alert-red"><strong>Title</strong><br />This is an other message</div>
			</div>
			
			<div class="box padd mrggh" id="SIco">
				<h2>Icons</h2>
				
			</div>
			
			<div class="box padd mrggh" id="SPag">
				<h2>Paginator</h2>
				<div id="Paginator"></div>
			</div>

	</div>
</div>



<div class="modal" id="WindowExample">
	<div class="modal-head">
		<button class="close" onclick="Chiara.modal.close();">x</button>
    	<h2>Modal window example</h2>
	</div>
	<div class="modal-body">
		Text and content
	</div>
	<div class="modal-foot">
		<div class="section group">
			<div class="col span_1_of_3 left">
				 <button class="btn btn-red" onclick=";">Left button</button>
			</div>
			<div class="col span_2_of_3">
				<button class="btn" onclick="Chiara.modal.close();">Done</button>
				<button class="btn btn-green" onclick="Chiara.modal.close();">Ok</button>
			</div>
		</div>
		
	</div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	Chiara.paginator('Paginator',{currentPage:1, pgTotalPage:10, pgTotalItem:5},'null');
});
</script>

<?php ViewModel::getContents('site/footer');  ?>

