<?php use Chiara\Core\ViewModel;
use App\Models\PhonePrefix;

ViewModel::getContents('site/header');
?>

<div class="row">
	<section id="main">
		<div class="rowH gridrow">
			
			
			<div style="text-align: center;">
				<h1 >System Error</h1>
				Ci scusiamo per l'inconveniente, ma qualcosa &egrave; andato storto :/<br />
				Ti chiediamo gentilmente di riprovare o di contattarci alla mail info@buonappetito.menu
			</div>
			
			<?php if(ViewModel::param("DEBUG")==1): ?>
			<div style="margin:20px;border:4px solid #ff9900;padding:10px;">
				<?php foreach(ViewModel::param('stack') as $s){
					echo $s.'<br />';
				}
				?>
			
				<strong>ERR NO</strong>: <?php echo ViewModel::param("ERRNO"); ?><br />
				<strong>ERR STR</strong>: <?php echo ViewModel::param("ERRSTR"); ?><br />
				<strong>ERR FILE</strong>: <?php echo ViewModel::param("ERRFILE"); ?><br />
				<strong>ERR LINE</strong>: <?php echo ViewModel::param("ERRLINE"); ?><br />
			</div>
			<?php endif;?>
			
		</div>
	</section>
</div>
<script type="text/javascript">

</script>

<?php ViewModel::getContents('site/footer');  ?>


