<?php use Chiara\Core\ViewModel;?>

			<div style="text-align: center;">
				<h1>System Error</h1>
			</div>
			
			<div style="margin:20px;border:4px solid #ff9900;padding:10px;">
				<?php foreach(ViewModel::param('stack') as $s){
					echo $s.'<br />';
				}
				?>
			
				<strong>ERR NO</strong>: <?php echo ViewModel::param("ERRNO"); ?><br />
				<strong>ERR STR</strong>: <?php echo ViewModel::param("ERRSTR"); ?><br />
				<strong>ERR FILE</strong>: <?php echo ViewModel::param("ERRFILE"); ?><br />
				<strong>ERR LINE</strong>: <?php echo ViewModel::param("ERRLINE"); ?><br />
			</div>
			


