<?php use Chiara\Core\ViewModel; ?>
<footer>
 <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
 	<img alt="Licenza Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" />
 </a>
 <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Chiara</span>  
 is distributed with License <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons</a>.
</footer>
<script type="text/javascript">
$(document).ready(function(){
	hljs.initHighlightingOnLoad();
});
</script>