<?php 
use Chiara\Core\ViewModel;
?>

<header>
	<div class="buttonsBar">
		<span class="btn-group">
			<a class="btn btn-large <?php echo ViewModel::param('section') == 'client' ? 'btn-orange' : ''?>" href="<?php echo ViewModel::getOption('urlbase') ?>/client/intro">Client</a>
			<a class="btn btn-large <?php echo ViewModel::param('section') == 'server' ? 'btn-orange' : ''?>" href="<?php echo ViewModel::getOption('urlbase') ?>/server/intro">Server</a>
		</span>
		
		<input type="text" class="search"  />
		
	</div>
</header>
