<?php use Chiara\Core\ViewModel;?>

<div class="box padd">

	<h1 class="center">Welcome to Demo &amp; Documentation</h1>
	
	
	<div class="mrggh center">
	
		
		<img src="<?php echo ViewModel::getOption('urlbase') ?>/img/logoUnified128.png" />
		<p>
		Chiara Framework is a complete web tool help you to develop software very fast.<br />
		Il framework is divided into two parts: <strong>Client side</strong> and <strong>Server side</strong> separately usable.
		</p>
		
	</div>
	
	<div class="mrggh center">

		<img width="128px" src="<?php echo ViewModel::getOption('urlbase') ?>/img/logoClientBig.png" />
		<p>
		Client side is a CSS3/JS tool's set for creating web responsive interface.<br />
		Fast and simple widgets help you to make all your ideas.<br />
		It is jQuery based.
		<br /><br />  
		<a class="btn btn-big btn-orange" href="<?php echo ViewModel::getOption('urlbase') ?>/client/intro">Click here for a demo</a>
		</p>
	
	</div>
	<div class="mrggh center">
	
		<img width="128px" src="<?php echo ViewModel::getOption('urlbase') ?>/img/logoServerBig.png" />
		<p>
		Server side has everything you need to make any kind of web service.<br />
		Request Routing, Caching, DB Conncetion, Translation e more.<br />
		Chiara Server side inspired by the most famous Zend Framework maintaining the basic operation, but much lighter. 
		<br /> <br /> 
		<a class="btn btn-big btn-orange" href="<?php echo ViewModel::getOption('urlbase') ?>/server/intro">Click here for documentation</a>
		</p>
	</div>	
	
</div>

